travis:
  secure:
    BINSTAR_TOKEN: RE35sdp9v6qX28uutrVA2/BIf9oQ2aPr94HGWgogi4zyDTDoOiYPzrRiMpI7zNEvn2m4kqsK3YoDrvrPcZIRp064h1hSNPVCxBHoV2tbtb6NPxD8N00nwtKvZn4G+CdloCb2MwWzZVA/V9j7jqMb4F1wUBO9bJoSXdp2GMA87Nu8Bija6dnaI3TGwF9tDqXhp4Y8+fLHL7p9yP9zFrihdszSgsSdiwixVFb7dPqT1TrIcXYZIp/vNZn/UTbkj3WMuuWkfxYN1xqG+4PPxTdoAxbybRHu6aS9Haj/jD9e4gm3f/RV5gjD68a9nT0MChPFu3R2WFYFXK6JFy+w6kch3SflZoGhi3yrO+GliiiNRVfe3QHv/Al8Xr7mmozQRM7aBi9PLnweg4oHDM4jSOKUOtkY2WLe8UChAAL0/YGB6Ta0nKDQWLlcDY8BbQH7QE+S4U1/3zZKu+0H0tGj/zikX7RwoTy+r75hCA8JOuXZHttpxIqdg5lS4BclnPSA/DSyBVz8o7pCxkflRK8IBLjGECsqtNMA+9s7JRbGZhSeL9bhKK61Q7/NmG9cV1+++MUC/7NvHOTBjfoX8JON8FrV8kzx555cLCdoTjfeYqYzxWC8OwQWgwY1f68wEJrtdjbnS/RQdgjqPd+nIAc0qzqt1YBUw1NUN56gKVFB1/cjkjU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
